### ISSUE TITLE
import error : No module named src.rest

### ISSUE THREAD

**Issue by tarun7singh** [michael-hacker/unsplash-python#1]
I am getting import error when trying to import this lbrary. Am i doing something wrong?
```
from unsplash_python.unsplash import Unsplash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tarball/.local/lib/python2.7/site-packages/unsplash_python/unsplash.py", line 8, in <module>
    from .src.rest        import Rest
ImportError: No module named src.rest
```

**Comment by tarun7singh** [comment]
solved. it was due to three versions of this library installed. now it's working good.
